### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by aquynh** [neoz/asm_ops#1]
nice work!

there is a typo, however: " ... In Ida screen, press Alt-N to active ARM assemble."
you must mean "to activate ASM assemble", or "to activate Asm_Ops", which is the name of this tool?

keep it up, cheers.

**Comment by neoz** [comment]
Thanks Anh Quỳnh.

**Comment by aquynh** [comment]
one recommendation is to rename the script file "assembler.py" to be the same with project name (so rename it to be "asm_ops.py"). so when users copy this file into plugins directory of IDA, they can still recognize it among hundreds scripts there.

another issue: this script overwrites the original opcode. README should emphasize this fact (that the binary will be updated)
